version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: n8n_postgres
    environment:
      POSTGRES_USER: n8n_user
      POSTGRES_PASSWORD: n8n_password
      POSTGRES_DB: n8n_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data  # Local folder for Postgres data
    restart: always

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_DATABASE: n8n_db
      DB_POSTGRESDB_USER: n8n_user
      DB_POSTGRESDB_PASSWORD: n8n_password
      GENERIC_TIMEZONE: "Europe/Berlin" # Adjust to your timezone
      N8N_BASIC_AUTH_ACTIVE: "true"    # Enable basic authentication
      N8N_BASIC_AUTH_USER: "admin"     # Set a username for authentication
      N8N_BASIC_AUTH_PASSWORD: "securepassword" # Set a strong password
    volumes:
      - ./n8n_data:/home/node/.n8n  # Local folder for n8n data
    restart: always
    depends_on:
      - postgres
