global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
  level: INFO

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443
    http:
      tls:
        certResolver: lets-encrypt

certificatesResolvers:
  lets-encrypt:
    acme:
      email: vallejo@smk.com.co
      storage: /acme.json
      caServer: https://acme-v02.api.letsencrypt.org/directory
      httpChallenge:
        entryPoint: web