global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: INFO

providers:
  docker:
    exposedByDefault: false
    network: n8n-network

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443

certificatesResolvers:
  lets-encrypt:
    acme:
      email: ${EMAIL}
      storage: /acme.json
      caServer: https://acme-v02.api.letsencrypt.org/directory
      httpChallenge:
        entryPoint: web