entryPoints:
  web:
    address: ":80"  # Correct address for HTTP
    http:
      redirections:
        entryPoint:
          to: web-secure
          scheme: https

  web-secure:
    address: ":443"  # Correct address for HTTPS

certificatesResolvers:
  letsencrypt:
    acme:
      email: "santiago.vallejo@smk.com.co"
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        entryPoint: web

http:
  routers:
    n8n:
      rule: "Host(`automations.smk.agency`)"
      entryPoints:
        - web-secure
      service: n8n
      tls:
        certResolver: letsencrypt

  services:
    n8n:
      loadBalancer:
        servers:
          - url: "http://n8n:5678"

providers:
  file:
    filename: /etc/traefik/traefik.yml
    watch: true

log:
  level: DEBUG
