log:
  level: DEBUG

entryPoints:
  web:
    address: "5678:80"
    http:
      redirections:
        entryPoint:
          to: web-secure
          scheme: https

  web-secure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "${TRAEFIK_EMAIL}"
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        entryPoint: web

http:
  routers:
    web-secure-router:
      rule: "Host(`${TRAEFIK_DOMAIN}`)"
      entryPoints:
        - web-secure
      service: n8n
      tls:
        certResolver: letsencrypt

  services:
    n8n:
      loadBalancer:
        servers:
          - url: "http://n8n:5678"

providers:
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
