log:
  level: INFO

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "${TRAEFIK_EMAIL}"
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        entryPoint: web

http:
  routers:
    n8n:
      rule: "Host(`${TRAEFIK_DOMAIN}`)"
      entryPoints:
        - websecure
      service: n8n
      tls:
        certResolver: letsencrypt

  services:
    n8n:
      loadBalancer:
        servers:
          - url: "http://n8n:5678"

providers:
  file:
    filename: /etc/traefik/traefik.yml
    watch: true